#!/usr/bin/env bash
# containers/apply.sh — Init Podman machine, install Docker Compose v2, build images on macOS.

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../common.sh"

STATE_FILE="$(state_file_path "containers.conf")"
DOCKER_COMPOSE_VERSION="2.37.0"
changes_made=0

if ! has_command podman; then
    log_warn "podman command not found — skipping"
    exit 0
fi

# Init Podman machine if none exists
machine_name="$(podman machine list --format '{{.Name}}' 2>/dev/null | head -1)"
if [[ -z "$machine_name" ]]; then
    log_info "Initialising Podman machine..."
    podman machine init
    changes_made=1
fi

# Start Podman machine if not running
machine_running="$(podman machine list --format '{{.Running}}' 2>/dev/null | head -1)"
if [[ "$machine_running" != "true" ]]; then
    log_info "Starting Podman machine..."
    podman machine start
    changes_made=1
fi

# Write ~/.testcontainers.properties with the live Podman socket path.
# podman-mac-helper would normally manage /var/run/docker.sock, but it
# hardcodes a path that's stale on podman 5.x (containers/podman#18784),
# so we write docker.host directly. Re-runs reconcile drift automatically.
TESTCONTAINERS_PROPS="${HOME}/.testcontainers.properties"
podman_socket="$(podman machine inspect --format '{{.ConnectionInfo.PodmanSocket.Path}}' 2>/dev/null || true)"
if [[ -n "$podman_socket" ]]; then
    desired_props="$(cat <<EOF
# Generated by lib/modules/containers/apply.sh — do not edit.
docker.host=unix://${podman_socket}
testcontainers.ryuk.disabled=true
EOF
)"
    current_props=""
    if [[ -e "$TESTCONTAINERS_PROPS" ]]; then
        current_props="$(cat "$TESTCONTAINERS_PROPS" 2>/dev/null || true)"
    fi
    if [[ "$current_props" != "$desired_props" ]]; then
        log_info "Writing ${TESTCONTAINERS_PROPS} (docker.host=${podman_socket})"
        rm -f "$TESTCONTAINERS_PROPS"
        printf '%s\n' "$desired_props" > "$TESTCONTAINERS_PROPS"
        changes_made=1
    fi
else
    log_warn "Could not read Podman socket path — skipping ~/.testcontainers.properties"
fi

# Install Docker Compose v2 standalone plugin.
# podman-compose lacks full Docker Compose v2 compatibility (e.g. --scale).
# Installing the real Docker Compose v2 binary as a CLI plugin takes priority.
COMPOSE_PLUGIN_DIR="${HOME}/.docker/cli-plugins"
COMPOSE_PLUGIN="${COMPOSE_PLUGIN_DIR}/docker-compose"
COMPOSE_ARCH="$(uname -m)"
COMPOSE_URL="https://github.com/docker/compose/releases/download/v${DOCKER_COMPOSE_VERSION}/docker-compose-darwin-${COMPOSE_ARCH}"

install_compose=0
if [[ ! -x "$COMPOSE_PLUGIN" ]]; then
    install_compose=1
elif ! "${COMPOSE_PLUGIN}" version 2>/dev/null | grep -q "${DOCKER_COMPOSE_VERSION}"; then
    install_compose=1
fi

if [[ $install_compose -eq 1 ]]; then
    log_info "Installing Docker Compose v${DOCKER_COMPOSE_VERSION} plugin..."
    mkdir -p "$COMPOSE_PLUGIN_DIR"
    if curl -fsSL "$COMPOSE_URL" -o "$COMPOSE_PLUGIN" && chmod +x "$COMPOSE_PLUGIN"; then
        log_ok "Docker Compose v${DOCKER_COMPOSE_VERSION} installed"
        changes_made=1
    else
        log_error "Failed to download Docker Compose v${DOCKER_COMPOSE_VERSION}"
    fi
fi

# Build container images
while IFS= read -r line; do
    IFS=':' read -r name build_ctx description <<< "$line"

    image="localhost/${name}:latest"
    build_dir="${PROVISION_DIR}/${build_ctx}"

    if podman image exists "$image" 2>/dev/null; then
        continue
    fi

    if [[ ! -d "$build_dir" ]]; then
        log_error "Build context not found: ${build_dir}"
        continue
    fi

    log_info "Building container image: ${name} (${description})"
    if podman build -t "$image" "$build_dir"; then
        log_ok "Built: ${name}"
        changes_made=1
    else
        log_error "Failed to build: ${name}"
    fi
done < <(parse_state_file "$STATE_FILE")

if [[ $changes_made -eq 0 ]]; then
    log_ok "All container images already built"
else
    log_ok "Container images applied"
fi
